version: '2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: loueatsville
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
  server:
    build: ./server
    command: ["./scripts/wait-for-it.sh", "db:5432", "--", "python", "src/manage.py runserver 0.0.0.0:8000"]
    volumes:
      - ./server:/www/app
    ports:
      - "8000:8000"
    depends_on:
      - "db"
  client:
    build: ./client
    command: npm start
    volumes:
      - ./client:/www/app
    ports:
      - "4200:4200"
    depends_on:
      - "server"
